FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y unzip wget && rm -rf /var/lib/apt/lists/*

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

COPY script/*.py .
COPY requirements.txt .
COPY firestore_key.json .
RUN touch /var/log/actions.log

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip 

CMD ["gunicorn", "--config", "gunicorn_config.py","app:app"]