FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y unzip wget && rm -rf /var/lib/apt/lists/*

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

COPY requirements.txt .
COPY script/*.py /app/
COPY .env /app/
COPY firestore_key.json /app/

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip 

EXPOSE 8080

CMD ["gunicorn", "--config", "gunicorn_config.py","app:app"]